sudo: false
language: node_js
node_js:
  - "12.18"

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn
  - npm install -g codecov
  - yarn install

script:
  - yarn test --watchAll=false --coverage
  - codecov
  - yarn build

notifications:
  email: false
