sudo: false
language: node_js
node_js:
  - "15.0.1"

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn
  - npm install -g codecov
  - yarn install

script:
  - yarn test:coverage
  - codecov
  - yarn build

notifications:
  email: false
